site_name: Today I Learned
theme:
  name: material
  language: ja
  icon:
    logo: material/note-edit
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
repo_name: doc-til
repo_url: https://github.com/mknsk0309/doc-til

nav:
  - Home: index.md
  - Develop Tips:
    - DevContainer:
      - 設定ファイルの書き方: develop-tips/DevContainer/設定ファイルの書き方.md
  - Programing Tips:
    - Ruby:
      - 実行環境: programing-tips/ruby/実行環境.md
      - Rubyの予約語: programing-tips/ruby/Rubyの予約語.md
      - オブジェクト: programing-tips/ruby/オブジェクト.md
      - メソッド: programing-tips/ruby/メソッド.md
      - 演算子: programing-tips/ruby/演算子.md
      - パーセント記法: programing-tips/ruby/パーセント記法.md
      - 正規表現: programing-tips/ruby/正規表現.md
      - 文字コード: programing-tips/ruby/文字コード.md
      - 文字列の操作: programing-tips/ruby/文字列の操作.md
      - n数値の操作: programing-tips/ruby/n数値の操作.md
      - 配列の操作: programing-tips/ruby/配列の操作.md
      - ハッシュの操作: programing-tips/ruby/ハッシュの操作.md
      - ディレクトリ・ファイルの操作: programing-tips/ruby/ディレクトリ・ファイルの操作.md
      - 例外処理: programing-tips/ruby/例外処理.md
      - 大域脱出: programing-tips/ruby/大域脱出.md
      - メソッドの可視性と組み込み関数: programing-tips/ruby/メソッドの可視性と組み込み関数.md
      - 数値型クラス: programing-tips/ruby/数値型クラス.md
    - Rails:
      - Railsコマンド: programing-tips/rails/Railsコマンド.md
      - Rails8で個人開発してみる:
        - Top: programing-tips/rails/rails8-dev-app/index.md
        - 開発環境構築: programing-tips/rails/rails8-dev-app/001_開発環境構築.md
        - RSpecの導入: programing-tips/rails/rails8-dev-app/002_RSpecの導入.md
        - Bootstrapの導入: programing-tips/rails/rails8-dev-app/003_Bootstrapの導入.md
        - i18nによる日本語化: programing-tips/rails/rails8-dev-app/004_i18nによる日本語化.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - mdx_truly_sane_lists:
      nested_indent: 2

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
